version: "3"

services:

  mongo0:
    container_name: mongo0
    image: mongo:4.2
    networks:
      mongo_network:
        ipv4_address: 172.16.238.10
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo1:
    container_name: mongo1
    image: mongo:4.2
    networks:
      mongo_network:
        ipv4_address: 172.16.238.11
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    container_name: mongo2
    image: mongo:4.2
    networks:
      mongo_network:
        ipv4_address: 172.16.238.12
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-express:
    image: mongo-express
    container_name: mongox
    restart: always
    ports:
      - 8082:8081
    environment:
      # fill in popup when opening webui (mongo express)
      ME_CONFIG_BASICAUTH_USERNAME: rootuser
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
      # admin credentials (mongo express)
      # ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      # db credentials (mongodb service)
      # ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongodb:27017/
      ME_CONFIG_MONGODB_URL: mongodb://172.16.238.10:27017/?replicaSet=rs0
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    networks:
      - mongo_network

networks:
  mongo_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"