services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo:4.2
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    networks:
      default:
    ports:
      - 8082:8081
    environment:
      # fill in popup when opening webui (mongo express)
      ME_CONFIG_BASICAUTH_USERNAME: rootuser
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
      # admin credentials (mongo express)
      # ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      # db credentials (mongodb service)
      # ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongodb:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?useUnifiedTopology=true
    depends_on:
      - mongo0
      - mongo1
      - mongo2

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volume_directory/mongo/data1/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./volume_directory/mongo/data1/configdb:/data/configdb
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volume_directory/mongo/data2/db:/data/db # Note the data2, it must be different to the original set.
      - ./volume_directory/mongo/data2/configdb:/data/configdb
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db", "--enableMajorityReadConcern", "false" ]
    volumes:
      - ./volume_directory/mongo/data3/db:/data/db
      - ./volume_directory/mongo/data3/configdb:/data/configdb